let data_container = document.getElementById('data_container');
let login_box = document.createElement('div');
let login_header = document.createElement('div');
let login_header_text = "Username and Password";
let login_title = document.createElement('h1');
let input_section = document.createElement('div');
let username_input = document.createElement('input');
let password_input = document.createElement('input');
let check_button = document.createElement('input');
let cancel_button = document.createElement('input');
let warning_box = document.createElement('div');
let warn_time_bar = document.createElement('div');
let warn_box_text =  document.createElement('p');
let image_container = document.createElement('div');
let home_image = document.createElement('div');
let home_text_container = document.createElement('div');
let home_text_container_two = document.createElement('div');
let home_text_container_three =  document.createElement('div');
let text_one = document.createElement('p');
let text_two = document.createElement('p');
let text_three = document.createElement('p');
let partners_container = document.createElement('div');
let partners_text_area = document.createElement('div');
let partners_text = document.createElement('p');
let partners_logos_area = document.createElement('div');
let partner_sec_one = document.createElement('div');
let partner_sec_two = document.createElement('div');
let partner_sec_three = document.createElement('div');
let render_link_container = document.createElement('a');
let render_logo = document.createElement('img');
let railway_link_container = document.createElement('a');
let railway_logo = document.createElement('img');
let github_link_container = document.createElement('a');
let github_logo = document.createElement('img');

github_link_container.setAttribute('href', 'https://github.com/EMIT2019/User-Security-API');
github_logo.setAttribute('src', 'resources/images/github.png');
railway_link_container.setAttribute('href', 'https://railway.app/');
railway_logo.setAttribute('src', 'resources/images/railway.png');
render_logo.setAttribute('src', 'resources/images/render.png');
render_link_container.setAttribute('href', 'https://render.com/');
home_text_container.setAttribute('id', 'home_text_container');
image_container.setAttribute('id', 'image_container');
home_image.setAttribute('id', 'home_image_sec');
warn_time_bar.setAttribute('id', 'warn_time_bar');
warning_box.setAttribute('id', 'warn_box');
check_button.setAttribute('type', 'button');
check_button.setAttribute('value', 'Sing In');
check_button.setAttribute('id', 'check_button');
cancel_button.setAttribute('type', 'button');
cancel_button.setAttribute('value', 'Cancel')
cancel_button.setAttribute('id', 'cancel_button');
username_input.setAttribute('type', 'text');
username_input.setAttribute('id', 'txt_username');
username_input.setAttribute('placeholder', 'Username');
password_input.setAttribute('type', 'password');
password_input.setAttribute('id', 'txt_password');
password_input.setAttribute('placeholder', 'Password');

github_logo.classList.add('logo');
render_logo.classList.add('logo');
railway_logo.classList.add('logo');
partners_logos_area.classList.add('partners_logos_area');
partners_text_area.classList.add('partners_text_area');
partners_container.classList.add('partners');
home_text_container_three.classList.add('home_text_container_three');
home_text_container_two.classList.add('home_text_container_two');
home_text_container.classList.add('home_text_container');
image_container.classList.add('image_container');
home_image.classList.add('home_image');
warning_box.classList.add('warn_box');
warn_time_bar.classList.add('warn_timer_bar');
check_button.classList.add('sing_button');
cancel_button.classList.add('cancel_button');
input_section.classList.add('login_input_sec');
login_title.classList.add('login_header_title');
login_header.classList.add('login_header');
login_box.classList.add('login');
username_input.classList.add('input');
password_input.classList.add('input');
warn_box_text.classList.add('warn_box_text');

warn_box_text.innerHTML = "Wrong username or password!";
text_one.innerHTML = "The top #1";
text_two.innerHTML = "in the software"
text_three.innerHTML = "and security industry!";
partners_text.innerHTML = "Working with";

data_container.appendChild(image_container);
data_container.appendChild(partners_container);
render_link_container.appendChild(render_logo);
partner_sec_one.appendChild(render_link_container);
github_link_container.appendChild(github_logo);
railway_link_container.appendChild(railway_logo);
partner_sec_two.appendChild(railway_link_container);
partner_sec_three.appendChild(github_link_container);
partners_logos_area.appendChild(partner_sec_one);
partners_logos_area.appendChild(partner_sec_two);
partners_logos_area.appendChild(partner_sec_three);
partners_text_area.appendChild(partners_text);
partners_container.appendChild(partners_text_area);
partners_container.appendChild(partners_logos_area);
image_container.appendChild(home_image);
home_text_container.appendChild(text_one);
home_text_container_two.appendChild(text_two);
home_text_container_three.appendChild(text_three);
image_container.appendChild(home_text_container);
image_container.appendChild(home_text_container_two);
image_container.appendChild(home_text_container_three);
login_title.innerHTML = login_header_text;
input_section.appendChild(username_input);
input_section.appendChild(password_input);
input_section.appendChild(check_button);
login_header.appendChild(login_title);
login_box.appendChild(login_header);
login_box.appendChild(input_section);
warning_box.appendChild(warn_box_text);
warning_box.appendChild(warn_time_bar);
login_box.appendChild(warning_box);
data_container.appendChild(login_box);
